# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'InstagramIntegration' do
    pod 'InstagramKit', '3.6.3'
end

target 'InstagramIntegrationTests' do

end

